-- Tables for Book with many-to-many genres and courses

CREATE TABLE Book(id INTEGER NOT NULL PRIMARY KEY, author VARCHAR(256) NOT NULL, title VARCHAR(256) NOT NULL, isbn VARCHAR(20));

CREATE TABLE Genre(id INTEGER NOT NULL PRIMARY KEY, name VARCHAR(256));

CREATE TABLE Course(id INTEGER NOT NULL PRIMARY KEY, name VARCHAR(256));

CREATE TABLE BookGenre(book_id INTEGER NOT NULL, genre_id INTEGER NOT NULL, FOREIGN KEY (book_id) REFERENCES Book(id), FOREIGN KEY (genre_id) REFERENCES Genre(id));

CREATE TABLE BookCourse(book_id INTEGER NOT NULL, course_id INTEGER NOT NULL, FOREIGN KEY (book_id) REFERENCES Book(id), FOREIGN KEY (course_id) REFERENCES Genre(id));